version: "3.8"
services:
  composer:
    image: composer:2.0
    volumes:
      - .:/app

  app:
    image: php:8.0-cli
    volumes:
      - .:/app
    working_dir: /app

  php-cs-fixer:
    image: oskarstark/php-cs-fixer-ga
    volumes:
      - .:/app
